### ISSUE TITLE
Find a way to implement Google Analytics 4 even though it isn't ready -or- find a new analytics platform entirely before July 2023

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/Nebula#2076]
Related/Dependent of #1500 and this makes #1962 redundant.

Google Analytics now (or will very soon) defaults to "Google Analytics 4" as the default property type (formerly "Apps + Web"). This type requires the gtag property, but Nebula currently only works with Universal Analytics.

As #1500 notes, we need to make sure that the Tasks API can be utilized to transition. There is (what still feels like a hack) a way to do this with Gtag, but I've been really hoping that a more direct approach would be natively possible. Google's Issue Tracker Tasks API inquiry: https://issuetracker.google.com/issues/119244062

Nebula's event tracking currently also triggers a GTM event hook– I wonder if that is still necessary with the Gtag library?

One additional note is that via Enhanced Measurement (noted in #1962) will eliminate the need for the Autotrack.js library (which does not support gtag anyway). That being said, we need to make sure than any of the Nebula settings and hooks that override aspects of Autotrack can do the same thing with Enhanced Measurement in Google Analytics itself.

# Documentation
- Overview: https://developers.google.com/analytics/devguides/collection/ga4
- Event Tracking (same as Gtag): https://developers.google.com/analytics/devguides/collection/ga4/events

# Implementation
So here is a checklist of things that need to be done to support Google Analytics 4 in Nebula:
- [x] Convert all analytics functions to use Gtag (#1500)
    - /inc/analytics.php (pageview, tasks)
    - /assets/js/nebula.js (event tracking)
    - /libs/Utilities/Analytics.php (some hooks, may not be much changing here)
- [ ] ~~Implement the Tasks API (#1500 also)~~
- [x] Remove Autotrack.js
    - Modify hooks to be compatible with Enhanced Measurement via GA itself
- [x] Figure out how Custom Dimensions migrate to [User Properties](https://developers.google.com/analytics/devguides/collection/ga4/user-properties)
- [x] Make sure Nebula automatically appends the `enablejsapi` query parameter to **all** Youtube videos every time
- [ ] ~~Update event tracking to match [recommended names and properties](https://support.google.com/analytics/answer/9267735)~~
- [x] Update `thisEvent` variables in Nebula event listeners to use better properties (now they we aren't locked into category, action, and label).
- [x] Remove the Nebula dimension index mapping array since we can use the parameter name directly now. Will need to figure out the best way to "activate" the ones we want– probably leave the Nebula Options interface and let the admin paste in the parameter name that they entered into GA.
- [x] No more `ga('set', 'dimension1', 'whatever');` so those can be stored in the `nebula` object and then passed via the next event (page_view or whatever).
- [ ] Add a Nebula Option to put Google Analytics into debug mode. This should be accompanied by a Nebula warning!
    - [x] When `?debug` query string appears, enable GA4 debug mode as described in #1684 

Note: In GA4, IP addresses are automatically anonymized.

**Comment by chrisblakley** [comment]
Looks like the new "Streams" use a "Measurement ID" (as opposed to a Tracking ID). This will mean that Nebula Options and variable names will need to change... right?

![Screen Shot 2020-10-17 at 6 13 54 PM](https://user-images.githubusercontent.com/6349678/96354436-b9a1c600-10a4-11eb-9a2b-d5ec5e37fed0.png)

https://support.google.com/analytics/answer/9539598

**Comment by chrisblakley** [comment]
User data retention options have also changed. Can only select between 2 months and 14 months for "event" data.

![Screen Shot 2020-10-17 at 6 16 38 PM](https://user-images.githubusercontent.com/6349678/96354463-fc639e00-10a4-11eb-86d9-23c904c553a9.png)

The label "Event Data" is what is concerning... I know Universal Analytics keeps the event data and only removes demographic data beyond the retention period, but this seems to apply that the actual event data itself may be removed...

**Comment by chrisblakley** [comment]
User Properties are created on the reporting-side (not the admin-side) here:
![Screen Shot 2020-10-17 at 6 22 41 PM](https://user-images.githubusercontent.com/6349678/96354546-d12d7e80-10a5-11eb-8fdd-6bf8a48a1a2e.png)

**Comment by chrisblakley** [comment]
## Events and "Goal" Conversions

Since there is no "View" column anymore in the admin section, it looks like goals/conversions are managed on the reporting side under Events > All Events. There is a column here where you can toggle which events are marked as conversions.

![Screen Shot 2020-10-17 at 6 30 42 PM](https://user-images.githubusercontent.com/6349678/96354662-143c2180-10a7-11eb-8be6-b1494683095b.png)

**Comment by chrisblakley** [comment]
## Debug Mode
This is a great idea so that dev servers can send actual data to GA without interfering with live data.

From the docs: https://support.google.com/firebase/answer/7201382?hl=en&utm_id=ad

### Via gtag.js for all events
Include a `'debug mode' = true` parameter; for example:

```js
gtag('config', 'G-12345ABCDE',{'debug_mode':true});
```

### Via gtag.js for individual events
```js
gtag('event', 'xyz', {
  'debug_mode':true
});
```

**Comment by chrisblakley** [comment]
## New Limits

- Properties: 99
- Conversions (Goals) per Property: 30 (in addition to the 5 defaults)
- Custom Dimensions/Metrics: Unlimited?
- User Properties: 25

**Comment by chrisblakley** [comment]
## Cross-Domain Tracking

It seems like GA4 would be good for cross-domain tracking (if we need multiple domains to send data to the same GA property). Looks like we could just set up a new stream for each data source, [but the documentation](https://support.google.com/analytics/answer/9213390) recommends (requires?) some kind of User ID that is passed between the websites... What about if we do not have user logins?

**Comment by chrisblakley** [comment]
## Google Analytics 4 Measurement Protocol

The Measurement Protocol still works with GA4, but looks like the API is back to Alpha, so it could drastically change between now and when becomes stable. For now, here is the documentation of how to send an event via the Measurement Protocol: https://developers.google.com/analytics/devguides/collection/protocol/ga4/sending-events?client_type=gtag#send_an_event

Nebula was sending a beacon for quality assurance usage tracking #2075 but eventually we can use Fetch for that.

```js
const measurement_id = `G-XXXXXXXXXX`;
const api_secret = `<secret_value>`;

fetch(`https://www.google-analytics.com/mp/collect?measurement_id=${measurement_id}&api_secret=${api_secret}`, {
  method: "POST",
  body: JSON.stringify({
    client_id: 'XXXXXXXXXX.YYYYYYYYYY',
    events: [{
      name: 'tutorial_begin',
      params: {},
    }]
  })
});
```

**Comment by chrisblakley** [comment]
### Tasks and Initial Pageview Send

After doing some initial testing, I'm not sure how the persistent data would be set since it happens in the `event_callback` function of the event being sent to GA... Additionally, the syntax is not the way the documentation requires.

```js
gtag('event', 'page_view', {
	'event_callback': function(){
		window['ga'](function(){
			var gtagTracker = window.ga.getByName('gtag_UA_36461517_3');
			gtagTracker.set('client_id', gtagTracker.get('clientId')); //This does not follow the proper syntax for a user property in gtag...
		});
	}
});
```

Since the documentation requires the custom property to be at the top-level of the object parameter (parameter 3), the above syntax may not even work at all. Is there a way to "set" the property like there was in Universal?

**Comment by chrisblakley** [comment]
# Hypothetical Reports
I want to list some typical reports we use in Universal Analytics and map them to how you'd find that data in a GA4 property.

**Key metrics (users, sessions, pageviews, bounce rate)?**
Formerly under Audience > Overview.

**Which acquisition channel has the highest conversion rate?**
First check the User Acquisition report using the "Medium" or "Source/Medium" dimensions:
![Screen Shot 2020-10-29 at 11 02 31 PM](https://user-images.githubusercontent.com/6349678/97655234-fec9de80-1a3a-11eb-8d5f-a24bf7756be6.png)

"Default Channel Grouping" is still available in certain reports such as Traffic Acquisition:
![Screen-Shot-2020-11-10-at-9 46 22-AM](https://user-images.githubusercontent.com/6349678/98689762-3c334380-233a-11eb-97f0-d4e607cb23ff.jpg)

Further details would be under Explore > Analysis > Template Gallery > Acquisition (under Use cases). I still need to try this myself to learn what additional customization is required after choosing that report type.

**Which UTM source/medium is performing the best?**
Again– check the User Acquisition report and/or use the explorer to build the data.

**What URLs are referral tracking coming from?**
Explore > Analysis > Template Gallery > Acquisition?

**What are the top landing pages on the Organic Search channel?**
I'm guessing you'd use the "Pages and Screens" report under Engagement, but I don't know how to segment to organic traffic yet– probably via "comparison" but I don't see an "organic search" option in that dropdown... Do we really need to make a custom analysis for this too?

**What is the average load time of the website?**

**Which page are users typically navigating to after landing on the home page?**

**What about the Content Drilldown report?**

**How does the bounce rate of each landing page compare?**

**What pages users exit from?**
I haven't tested this yet myself, but looks like it would be found under the Explore > Analysis > Template Gallery > User Behavior (under "Use Cases"). ...Do we really have to "create" all of these reports on every single property we manage?? I understand that GA4 caters to both web and apps, but this sounds like a huge time requirement... Can't "web" have better default reports?

**Internal search usage?**

**How can I see an individual user's sessions?**
The User Explorer still exists, but the report must be "created" under the Explore > Analysis > Template Gallery > User Explorer (under "Techniques)

**Where can I see exceptions (errors) that we are tracking?**

**Will there be a community shared report template gallery like exists in Unversal now?**
Since managing dozens of properties could get tedious setting up the same reports over and over in the Explorer I wonder if we'll see a community-based (or even user-based) saved templates to make setting these up a little faster...?

**Comment by chrisblakley** [comment]
# Questions
Here are my questions from my notes below. I'll try to answer them here as a quick-reference in the future (or for anyone else who stumbles upon this). I will not feel confident switching Nebula to GA4 until I can answer all of these questions.

**Q.) Will we ever get direct access to the Tasks API?**
[This issue is currently assigned](https://issuetracker.google.com/issues/119244062), but no idea if anything will change from it. IMO, this may be the primary hurdle for Nebula updating to GA4...

**Q.) Does data itself (events) get removed from GA reports after the retention period, or just their association with that user (cookie)?**

**Q.) What is the difference between a "User Property" and a "Custom Dimension"?**
My current guess is that a User Property is the same as the old user-scoped dimension in UA, and a custom dimension now refers to an "event" scoped dimension... I'm not sure what an event-scope is... is it a "hit"? If so, where did "session" scoped dimensions go (I use those much more commonly)...

**Q.) How are custom dimensions scoped?**

**Q.) What does the event "name" correspond to? (Ex: Category, Action, or Label)**
The event name is the equivalent of the UA "action". There is no such thing as a category, action, or label anymore– only custom parameters: https://support.google.com/analytics/answer/10106689?hl=en&ref_topic=9328240

![Screen Shot 2020-10-18 at 12 08 26 AM](https://user-images.githubusercontent.com/6349678/96358573-b293ab80-10d6-11eb-957d-8aacda3a5ddc.png)

GA4 has a limit of 500 event names per property!

**Q.) Are custom parameters (for events) the same as custom dimensions/metrics or are they different?**

**Q.) Where are filters (formerly in Views), and how do we filter out internal traffic?**
I thought they would be in the "Data Streams" setting within each property, but when I click on the "All Filters" setting under the Account, I see this message: "Filters cannot be applied to App + Web [GA4] Properties."

However, if you click into the Data Stream, and then choose "Tagging Settings" in the "Additional Settings" section, you can select "Define internal traffic" which would still appear in GA reports, but would be marked as internal.

![Screen Shot 2020-10-29 at 10 56 27 PM](https://user-images.githubusercontent.com/6349678/97654918-53b92500-1a3a-11eb-9363-882476174836.png)

![Screen Shot 2020-10-29 at 10 56 07 PM](https://user-images.githubusercontent.com/6349678/97654923-56b41580-1a3a-11eb-944b-67ac85465930.png)

**Q.) Are brand terms no longer able to be added to allow for custom channel groupings of "Branded Paid Search" and "Generic Paid Search"?**

**Q.) Are Calculated Metrics going away?**
I didn't use these much, but Nebula does have some documentation on them that may need to be updated.

**Q.) Is internal Site Search reporting going away?**
Since that was a setting under "View", the setting must have been moved. [In this documentation page](https://support.google.com/analytics/answer/9234069?hl=en&ref_topic=9756175), site search is still referenced, and the query parameter can be changed in the "Advanced Settings" area... wherever that is.

**Q.) How is "Engagement" defined?**
Sessions that last longer than 10 seconds, or have a conversion event, or had 2 or more pageviews.
<img width="419" alt="Screen Shot 2020-11-10 at 9 58 16 AM" src="https://user-images.githubusercontent.com/6349678/98690835-60dbeb00-233b-11eb-9571-a92743bd0bfd.png">

**Comment by chrisblakley** [comment]
Noting this here as a custom field formula for Google Data Studio. This can help recreate the "Default Channel Grouping" dimension that is sorely lacking from GA4:

```
CASE 
WHEN ((Source="direct" AND Medium="(not set)") OR Medium="(none)") THEN "Direct" 
WHEN Medium="organic" THEN "Organic Search" 
WHEN (Social Source Referral="Yes" OR REGEXP_MATCH(Medium,"^(social|social-network|social-media|sm|social network|social media)$")) THEN "Social" 
WHEN Medium="email" THEN "Email" 
WHEN Medium="affiliate" THEN "Affiliates" 
WHEN Medium="referral" THEN "Referral" 
WHEN (REGEXP_MATCH(Medium,"^(cpc|ppc|paidsearch)$") AND Ad Distribution Network!="Content") THEN "Paid Search" 
WHEN REGEXP_MATCH(Medium," ^(cpv|cpa|cpp|content-text)$") THEN "Other Advertising" 
WHEN (REGEXP_MATCH(Medium,"^(display|cpm|banner)$") OR Ad Distribution Network="Content") THEN "Display" ELSE "(Other)" 
END
```

Here is the logic source from Google's documentation: https://support.google.com/analytics/answer/3297892

**Comment by chrisblakley** [comment]
Per a Google rep, the ballpark of Q2 2021 was floated for a broader feature set.

They also mentioned at least 18 months before the idea of Universal deprecation would be in the conversation. I imagine it will still work for a very long time (since Classic still works)...

**Comment by chrisblakley** [comment]
Looks like GA4 will have event editing right from within Google Analytics– so changing the name of the event name after the data has been sent (without needing to modify website code).

![Screen Shot 2021-01-29 at 6 19 20 PM](https://user-images.githubusercontent.com/6349678/106337173-8a335580-625e-11eb-81b7-0c2af03cdcb3.png)

![Screen Shot 2021-01-29 at 6 20 21 PM](https://user-images.githubusercontent.com/6349678/106337233-ab944180-625e-11eb-9dda-c07ec3630937.png)

**Comment by chrisblakley** [comment]
New demo account available: https://analytics.google.com/analytics/web/demoAccount

https://support.google.com/analytics/answer/6367342?linkId=110255766

**Comment by chrisblakley** [comment]
User-scoped custom dimensions are now available in GA4:
https://support.google.com/analytics/answer/10075209

![EumvemEXIAUYQMG](https://user-images.githubusercontent.com/6349678/108580576-0ff46f00-72fa-11eb-970e-22f6be27899a.jpg)

**Comment by chrisblakley** [comment]
Data filtering is now available as well, but is limited to exclude internal traffic and/or dev server traffic:
![Screen Shot 2021-02-19 at 9 37 05 PM](https://user-images.githubusercontent.com/6349678/108580769-f6075c00-72fa-11eb-902a-0c64f000b98e.png)

![Screen Shot 2021-02-19 at 9 38 36 PM](https://user-images.githubusercontent.com/6349678/108580765-f30c6b80-72fa-11eb-91a5-b8d2fea8296d.png)

**Comment by chrisblakley** [comment]
An API key will be needed to use the Measurement Protocol API. It is available under Admin > Data Streams > (Click the data stream you want) > Measurement Protocol API secrets

![Screen Shot 2021-02-19 at 9 40 58 PM](https://user-images.githubusercontent.com/6349678/108580834-4bdc0400-72fb-11eb-8b3c-3cee143f4ae7.png)

**Comment by chrisblakley** [comment]
Cross-Domain tracking (formerly GA Linker) is set up under Admin > Data Streams > (Click the data stream you want) > More Tagging Settings > Configure your domains

![Screen Shot 2021-02-19 at 9 43 35 PM](https://user-images.githubusercontent.com/6349678/108580891-8f367280-72fb-11eb-98ca-ff819814b0aa.png)

**Comment by chrisblakley** [comment]
![Screen Shot 2022-03-16 at 1 58 45 PM](https://user-images.githubusercontent.com/6349678/158658713-5e57413b-4843-4159-98ae-7724212442b1.png)

Google announced today that Universal Analytics will no longer be available as of July 1, 2023.

-Until July 1, 2023, you can continue to use and collect new data in your Universal Analytics properties.

- After July 1, 2023, you'll be able to access your previously processed data in your Universal Analytics property for at least six months. We know your data is important to you, and we strongly encourage you to [export](https://support.google.com/analytics/answer/11583528#export) your historical reports during this time.

- In the coming months, we'll provide a future date for when existing Universal Analytics properties will no longer be available. After this future date, you'll no longer be able to see your Universal Analytics reports in the Analytics interface or access your Universal Analytics data via the API.

https://support.google.com/analytics/answer/11583528

GA4 is nowhere close to being ready for this, but I'm guessing the GDPR lawsuits in the EU is what is hastening Google's decision.

Might be time to look into alternate platforms ahead of July 2023. What a nightmare this whole thing is.

**Comment by chrisblakley** [comment]
## Alternative Analytics Platforms if it comes to that

Ideally it would be a free, cloud-based platform that is privacy compliant and allows for the advanced detections (events, custom dimensions) that Nebula has developed. The biggest thing here is we're trying to replace a literal industry standard, which is a very tall order.

As I research these, I'll update with some details and gut reactions.

- Matomo (https://matomo.org/)
- Adobe Analytics (Hahaha, no 🤮 )
- Plausible (https://plausible.io/)
- Microsoft Clarity
- Clicky (https://clicky.com/)
- Heap (https://heap.io/)
- Simple Analytics (https://simpleanalytics.com/)
- Fathom (https://usefathom.com/)
- SmartLook (https://www.smartlook.com/)

...Also I can't wait to see whose sales teams comment on this claiming to be long-time users of Nebula...

**Comment by chrisblakley** [comment]
As we research alternatives, Nebula will begin shifting support to GA4 starting May 1, 2022 (in about a month and a half). Nebula v10 will be the last version that uses Universal Analytics 😢

**Comment by chrisblakley** [comment]
# Most Important GA Reports

Noting the most important GA reports in my opinion that we would either need to find in another platform or recreate within GA4 itself as closely as possible.

## Audience Overview
This is essential for key metrics and the visual timeline chart.

![Screen Shot 2022-03-19 at 2 01 38 PM](https://user-images.githubusercontent.com/6349678/159133007-f378e734-be9b-452f-96c4-1f1d617e5f88.png)

## Acquisition Channels
Probably the most useful report in all of GA. Default channel groupings with individual metrics including bounce rate (or engagement rate or whatever) and the conversion **_rate_** for various (or all combined) goals.

![Screen Shot 2022-03-19 at 2 04 04 PM](https://user-images.githubusercontent.com/6349678/159133093-d24cbf55-538f-4fc1-948d-2001054b8c99.png)

## Mobile Overview
Breakdown of device categories with individual metrics including bounce rate and conversion rates.

![Screen Shot 2022-03-19 at 2 05 32 PM](https://user-images.githubusercontent.com/6349678/159133134-41840925-24cd-4bbe-9c6b-8d7353116c32.png)

Nice-to-have would be a bounce rate comparison, too.

![Screen Shot 2022-03-19 at 2 06 17 PM](https://user-images.githubusercontent.com/6349678/159133173-e6ecbee7-81b2-44e3-8a15-e12b688cfed8.png)

## Top Content
Showing the most popular pages on the site. Nice to have the page value metric, too.

![Screen Shot 2022-03-19 at 2 06 53 PM](https://user-images.githubusercontent.com/6349678/159133253-35c74c62-ca7e-4a32-af44-78b2a565663b.png)

## Content Drilldown
Showing the most popular **_sections_** on the site.' Each row in this report is a URL directory and includes all pages within that directory. Especially useful for organic acquisition pages like blog posts.

![Screen Shot 2022-03-19 at 2 09 07 PM](https://user-images.githubusercontent.com/6349678/159133315-7490c292-0dfd-45be-8a18-9997ef865a9e.png)

## Landing Pages
This is another essential report to determine which landing pages are contributing to conversions and also which have the highest bounce rates.

![Screen Shot 2022-03-19 at 2 11 48 PM](https://user-images.githubusercontent.com/6349678/159133392-be580c86-6b90-47bd-bf0d-17dfebbe29fa.png)

![Screen Shot 2022-03-19 at 2 12 42 PM](https://user-images.githubusercontent.com/6349678/159133422-19b624ae-a50c-4925-8d5c-226a1041f166.png)

## Navigation Summary
This is important to see pages being viewed before/after a specific page. Useful to see what the next pages viewed after the home page (or a particular landing page), for example.

![Screen Shot 2022-03-19 at 2 14 44 PM](https://user-images.githubusercontent.com/6349678/159133476-882af5a2-e94b-4ad8-95eb-5321842ffd15.png)

## Site Search
Shows how often internal searches occur, what keywords are being searched for, as well as how often search refinements (subsequent searches) happen, how often users are leaving from internal SERP, and other useful metrics.

![Screen Shot 2022-03-19 at 2 16 05 PM](https://user-images.githubusercontent.com/6349678/159133593-57502311-09bb-4590-bae5-c7e963fd4f4c.png)

![Screen Shot 2022-03-19 at 2 15 57 PM](https://user-images.githubusercontent.com/6349678/159133595-43e5ed57-1b1b-4229-8789-3b9277b19d0b.png)

## Events
These are essential and must drilldown from Category -> Action -> Label. Ideally it would report on total and unique events.

![Screen Shot 2022-03-19 at 2 23 28 PM](https://user-images.githubusercontent.com/6349678/159133774-9457bd04-4c02-412e-96b9-4e7dcee694db.png)

## Goals
These are obviously essential. From a setup standpoint, these should be able to be destination pages or events and be able to match full pages or partial/regex strings. This is actually one thing I think even Universal Analytics doesn't have great reports on. It's mostly useful as contextual metrics within other reports. 

![Screen Shot 2022-03-19 at 2 26 04 PM](https://user-images.githubusercontent.com/6349678/159133872-d1b31c30-cd4f-4214-8a1a-57340b737de2.png)

## Various Ecommerce Reports
Obviously these are useful for a range of product/sales reporting.

![Screen Shot 2022-03-19 at 2 19 05 PM](https://user-images.githubusercontent.com/6349678/159133722-678141d1-f9d4-4e3f-a083-051d37598c78.png)

![Screen Shot 2022-03-19 at 2 19 22 PM](https://user-images.githubusercontent.com/6349678/159133725-cecbab18-4a58-4f52-a2ca-55ebc4f6ba23.png)

![Screen Shot 2022-03-19 at 2 19 29 PM](https://user-images.githubusercontent.com/6349678/159133726-f27bbb0d-b30a-4081-935d-2da166c624e6.png)

![Screen Shot 2022-03-19 at 2 19 51 PM](https://user-images.githubusercontent.com/6349678/159133731-56be26dd-6f4f-440f-a055-2a67b892ebf2.png)

**Comment by chrisblakley** [comment]
In the transition period, this is a useful setting, too:

Collect Universal Analytics events
![Screen Shot 2022-04-01 at 8 25 24 AM](https://user-images.githubusercontent.com/6349678/161262979-cdf2e314-f0b6-49cf-9fea-200411a010a8.png)

Data Streams (under Property admin) > Click right arrow on the data stream > More Tattings Settings > Collect Universal Analytics events

**Comment by chrisblakley** [comment]
As of this moment (not yet committed), there are no more JavaScript instances of Universal Analytics. Everything in JS (and most PHP) has been updated to GA4.

The remaining steps include the PHP Measurement Protocol for some supplemental data and still need a massive amount of testing.

**Comment by chrisblakley** [comment]
At this point, Nebula is fully functioning in GA4 now including the Measurement Protocol for usage and server-side data. Need to do a ton of testing, and although that was a major lift, now the hard part begins of trying to find how to actually report on that data in the platform itself.

Why can't we just have default reports like before? I'd dare say that I would actually _like_ GA4 if we could just get the default reports from the previous platform...

**Comment by chrisblakley** [comment]
Is there a way to annotate important dates in GA4? I don't see one...

**Comment by chrisblakley** [comment]
Closing this as GA4 has now been implemented in Nebula officially, but there is still a long, confusing road ahead on the reporting side. Seems like every day I'm finding new, frustrating limitations with GA4... Definitely stifling motivation.

I'm hoping the community continues to push hard for basic features. Even searching by Measurement ID doesn't work. It's such a shame that every other aspect of design and development are getting such cool new features, and in analytics it feels like features are only being taken away. GA4 _could_ have been so good, too.

...and I say all this as a **huge** fan of Google Analytics.

If anyone from the Google Analytics team ever finds this, please reach out! I would love to have an earnest conversation about the platform!!

**Comment by chrisblakley** [comment]
Referral exclusion, session timeout, internal IP, and other settings are available here:

![Screen Shot 2022-07-13 at 10 52 48 AM](https://user-images.githubusercontent.com/6349678/178764745-ac110930-55df-4d4b-92cb-1572ed6940bf.png)

This is inside of the Data Streams property section.
